### ISSUE TITLE
Would you mind releasing username "fscheck"?

### ISSUE THREAD

**Issue by kurtschelfthout** [f-scheck/yv#3]
I run an open source project called "fscheck" and would like to start an organization called "fscheck".

https://github.com/fsharp/FsCheck

You would be doing me a huge favour.

Thanks for considering.

Best, Kurt

**Comment by f-scheck** [comment]
Hello Kurt,

I have changed my username to f-scheck!
Good Luck with ur project.

All the best,
Friedrich

**Comment by kurtschelfthout** [comment]
That's brilliant. I just created fscheck organization. Thanks a lot!
